# Generated by Django 3.0 on 2020-07-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_expert_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='valuation_status',
            field=models.CharField(choices=[('pass', '评审通过'), ('nopass', '评审不通过'), ('unvaluated', '待评审')], default='unvaluated', max_length=20, verbose_name='评审状态'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('ok', '已确认'), ('nok', '已排除'), ('unknow', '待确认')], default='unknow', max_length=20, verbose_name='确认状态'),
        ),
    ]
