# Generated by Django 3.0 on 2020-07-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_auto_20200721_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='valuation_status',
            field=models.CharField(default='待评审', max_length=20, verbose_name='评审状态'),
        ),
    ]
