# Generated by Django 3.0 on 2020-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_auto_20200721_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='valuation_status',
            field=models.CharField(choices=[('pass', '评审通过'), ('nopass', '评审不通过'), ('unvaluated', '待评审')], default='unvaluated', max_length=20, verbose_name='评审状态'),
        ),
    ]
