# Generated by Django 3.0 on 2020-07-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_auto_20200721_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=10000, null=True, verbose_name='评审意见'),
        ),
    ]
