# Generated by Django 3.0 on 2020-06-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('responser', models.CharField(max_length=100)),
                ('desp', models.CharField(max_length=1000)),
            ],
        ),
    ]
