# Generated by Django 3.0 on 2020-06-28 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='发起时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='desp',
            field=models.CharField(max_length=1000, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=500, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='program',
            name='responser',
            field=models.CharField(max_length=100, verbose_name='项目负责人'),
        ),
    ]
