# Generated by Django 3.0 on 2020-06-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='excluded_experts',
        ),
        migrations.RemoveField(
            model_name='program',
            name='selected_experts',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
