# Generated by Django 3.0 on 2020-06-28 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20200628_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='评标截止时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='所属地'),
        ),
        migrations.AddField(
            model_name='program',
            name='money',
            field=models.CharField(max_length=100, null=True, verbose_name='招标金额'),
        ),
        migrations.AddField(
            model_name='program',
            name='seq',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='项目编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='评标开始时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='desp',
            field=models.CharField(max_length=1000, null=True, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_date',
            field=models.DateField(verbose_name='创建时间'),
        ),
    ]
