# Generated by Django 3.0 on 2020-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20200628_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
