# Generated by Django 3.0 on 2020-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visible', models.BooleanField(default=True)),
                ('seq', models.CharField(max_length=100, verbose_name='项目编号')),
                ('name', models.CharField(max_length=500, verbose_name='项目名称')),
                ('desp', models.CharField(max_length=1000, null=True, verbose_name='项目描述')),
                ('responser', models.CharField(max_length=100, verbose_name='项目负责人')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='所属地')),
                ('money', models.CharField(max_length=100, null=True, verbose_name='招标金额')),
                ('program_date', models.DateField(verbose_name='创建时间')),
                ('start_date', models.DateField(verbose_name='评标开始时间')),
                ('end_date', models.DateField(verbose_name='评标截止时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
    ]
