# Generated by Django 3.0 on 2020-06-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('program', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('input_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcluedeExpert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('desp', models.CharField(max_length=500)),
                ('excluded_program_list', models.ManyToManyField(related_name='excluded', through='experts.ExcluedeExpert', to='program.Program')),
                ('selected_program_list', models.ManyToManyField(related_name='selected', through='experts.Comments', to='program.Program')),
            ],
        ),
        migrations.AddField(
            model_name='excluedeexpert',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.Expert', verbose_name='排除的评审专家'),
        ),
        migrations.AddField(
            model_name='excluedeexpert',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program', verbose_name='排除的项目名称'),
        ),
        migrations.AddField(
            model_name='comments',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.Expert', verbose_name='评审专家'),
        ),
        migrations.AddField(
            model_name='comments',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program', verbose_name='项目名称'),
        ),
    ]
