# Generated by Django 3.0 on 2020-06-21 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20200621_0226'),
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='excluded_program_list',
            field=models.ManyToManyField(related_name='excluded', to='program.Program'),
        ),
        migrations.AddField(
            model_name='expert',
            name='selected_program_list',
            field=models.ManyToManyField(related_name='selected', to='program.Program'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
                ('input_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.Expert')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.Program')),
            ],
        ),
    ]
