# Generated by Django 3.0 on 2020-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': '专家', 'verbose_name_plural': '专家'},
        ),
        migrations.RemoveField(
            model_name='expert',
            name='desp',
        ),
        migrations.AddField(
            model_name='expert',
            name='degree',
            field=models.CharField(choices=[('benke', '本科'), ('shuoshi', '硕士'), ('boshi', '博士'), ('boshihou', '博士后'), ('other', '其他')], default='other', max_length=500, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='expert',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='expert',
            name='level',
            field=models.CharField(choices=[('chuji', '初级职称'), ('zhongji', '中级职称'), ('gaoji', '高级职称'), ('jiaoshou', '教授'), ('shuodao', '硕士生导师'), ('bodao', '博士生导师'), ('yuanshi', '院士'), ('other', '其他类')], default='other', max_length=500, verbose_name='职务等级'),
        ),
        migrations.AddField(
            model_name='expert',
            name='program_type',
            field=models.CharField(choices=[('ligong', '理工类'), ('wenshi', '文史类'), ('yishu', '艺术类'), ('other', '其他')], default='other', max_length=500, verbose_name='专业类型'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.CharField(max_length=10000, verbose_name='评审意见'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='input_date',
            field=models.DateField(auto_now=True, verbose_name='评审日期'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='联系地址'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(max_length=100, verbose_name='专家姓名'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='unit',
            field=models.CharField(max_length=100, verbose_name='工作单位'),
        ),
    ]
