# Generated by Django 3.0 on 2020-07-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_auto_20200628_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': '专家评审意见', 'verbose_name_plural': '专家评审意见'},
        ),
        migrations.AlterModelOptions(
            name='excluedeexpert',
            options={'verbose_name': '专家排除表', 'verbose_name_plural': '专家排除表'},
        ),
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('ok', '已确认'), ('busy', '已排除'), ('unknow', '待确认')], default='unknow', max_length=500, verbose_name='评审状态'),
        ),
    ]
