# Generated by Django 3.0 on 2020-07-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_remove_expert_excluded_program_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='visible',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
