# Generated by Django 3.0 on 2020-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_program_visible'),
        ('experts', '0005_expert_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='excluded_program_list',
            field=models.ManyToManyField(related_name='excluded', through='experts.ExcluedeExpert', to='program.Program'),
        ),
    ]
